# Use Python 3.11 image as base
FROM python:3.11

RUN mkdir /bite
# Set working directory
WORKDIR /bite

# Set environment variables
ENV PYTHONUNBUFFERED 1
ENV FIREBASE_ACCOUNT_TYPE=$FIREBASE_ACCOUNT_TYPE
ENV FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
ENV FIREBASE_PRIVATE_KEY_ID=$FIREBASE_PRIVATE_KEY_ID
ENV FIREBASE_PRIVATE_KEY = $V
ENV FIREBASE_CLIENT_EMAIL=$FIREBASE_CLIENT_EMAIL
ENV FIREBASE_CLIENT_ID=$FIREBASE_CLIENT_ID
ENV FIREBASE_AUTH_URI=$FIREBASE_AUTH_URI
ENV FIREBASE_TOKEN_URI=$FIREBASE_TOKEN_URI
ENV FIREBASE_AUTH_PROVIDER_X509_CERT_URL=$FIREBASE_AUTH_PROVIDER_X509_CERT_URL
ENV FIREBASE_CLIENT_X509_CERT_URL=$FIREBASE_CLIENT_X509_CERT_URL
ENV GOOGLE_OAUTH2_CLIENT_ID=$GOOGLE_OAUTH2_CLIENT_ID
ENV GOOGLE_OAUTH2_CLIENT_SECRET=$GOOGLE_OAUTH2_CLIENT_SECRET
ENV GOOGLE_API_KEY=$GOOGLE_API_KEY
ENV GOOGLE_AUTH_DOMAIN=$GOOGLE_AUTH_DOMAIN
ENV GOOGLE_DATABASE_URL=$GOOGLE_DATABASE_URL
ENV GOOGLE_PROJECT_ID=$GOOGLE_PROJECT_ID
ENV GOOGLE_STORAGE_BUCKET=$GOOGLE_STORAGE_BUCKET
ENV GOOGLE_MESSAGING_SENDER_ID=$GOOGLE_MESSAGING_SENDER_ID
ENV GOOGLE_APP_ID=$GOOGLE_APP_ID
ENV GOOGLE_MEASUREMENT_ID=$GOOGLE_MEASUREMENT_ID
ENV DJANGO_SECRET_KEY = $DJANGO_SECRET_KEY

# Copy application files to container
COPY . ./
COPY /bite/api/api .env
COPY /firebase/credentials.json .
COPY /firebase/firebase_init.py .
COPY requirements.txt /api

RUN apt-get update && apt-get upgrade -y && apt-get install -y \
libsqlite3-dev

RUN pip install -U pip setuptools

# Install required packages
RUN pip install -r /api/requirements.txt

ADD . /api/

# Expose port
EXPOSE 8000

# Start the Django development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]    