# Generated by Django 4.1 on 2022-08-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='ano',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='created',
            field=models.DateTimeField(auto_created=True, blank=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
