# Generated by Django 4.1 on 2022-08-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0002_alter_veiculo_ano_alter_veiculo_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='descricao',
            field=models.TextField(),
        ),
    ]
