# Generated by Django 4.1 on 2022-08-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0003_alter_veiculo_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
