# Generated by Django 4.1 on 2022-08-04 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0005_alter_veiculo_created_alter_veiculo_vendido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 4, 17, 28, 40, 139785)),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='vendido',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
