# Generated by Django 4.1 on 2022-08-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApi", "0007_alter_veiculo_created_alter_veiculo_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="veiculo",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
